<package format="3">
  <name>hsrb_cgos_driver</name>
  <version>3.0.0</version>
  <description>Robot hardware class for Concatech IO driver</description>
  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>
  <license>BSD 3-clause Clear License</license>

  <author>Tamaki Nishino</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>ros2_control</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>